title: AI Atlas
description: >
  A list of useful AI tools from across the web
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ai-atlas.mosn.me" # the base hostname & protocol for your site

theme: jekyll-garden

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-garden

# Specify where Jekyll should find the theme
remote_theme: Jekyll-Garden/jekyll-garden

# Google Tag Manager
google_tag_manager_id: "GTM-NJLLKSJ9"

# GitHub Pages configuration
exclude:
  - theme/
  - README.md  # Exclude README from being processed as a Jekyll page