name: Sync README to Website Repository

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source repository (AI-Atlaas/AI-Atlaas)
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: AI-Atlaas/AI-Atlaas
          token: ${{ secrets.AI_SYNC }}

      # Checkout the target repository (static_site)
      - name: Checkout website repository
        uses: actions/checkout@v2
        with:
          repository: AI-Atlaas/static_site
          token: ${{ secrets.AI_SYNC }}
          path: static_site

      # Copy and transform README to the website repo
      - name: Prepare and copy README
        run: |
          mkdir -p static_site/src

          # Add front matter and copy content
          echo "---" > static_site/src/index.md
          echo "layout: layout.njk" >> static_site/src/index.md
          echo "title: AI Atlas" >> static_site/src/index.md
          echo "---" >> static_site/src/index.md
          echo "" >> static_site/src/index.md
          cat README.md >> static_site/src/index.md

      # Commit and push changes
      - name: Commit and push
        run: |
          cd static_site
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/index.md
          git commit -m "Sync README with layout from AI-Atlaas repo" || echo "No changes to commit"
          git push origin main
