name: Sync README to Website Repository

on:
  push:
    branches:
      - main  

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 2
        uses: actions/checkout@v2
        with:
          repository: AI-Atlaas/AI-Atlaas
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy and rename README to repository 1
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
        run: |
          git clone https://$GH_USERNAME:$FINE_GRAINED_PAT@github.com/AI-Atlaas/ai-atlas-site.git
          mkdir -p ai-atlas-site/pages/docs
          cp README.md ai-atlas-site/pages/docs/list.md
          cd ai-atlas-site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pages/docs/list.md  
          git commit -m "Update README from AI-Atlaas/AI-Atlaas"
          git push https://$GH_USERNAME:$FINE_GRAINED_PAT@github.com/AI-Atlaas/ai-atlas-site.git
